name: GWeasy
channels:
  - conda-forge
  - anaconda
dependencies:
  - python = 3.9
  - gwpy
  - gwosc
  - nds2-client
  - python-nds2-client
  - pandas
  - python-framel
  - pip
  - pillow
  - pip:
      - -r requirements.txt
