.TH "C:/Users/HP/Desktop/docs/GWeasy/GWeasy.py" 3 "Version v3.0.1" "GWeasy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/HP/Desktop/docs/GWeasy/GWeasy.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGWeasy\&.Application\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.TerminalFrame\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.OmicronApp\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.GravfetchApp\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.GWOSCApp\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.Omiviz\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.TimeSrswaveform\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.FFT\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.PSDs\fP"
.br
.ti -1c
.RI "class \fBGWeasy\&.Spectrogram\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGWeasy\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGWeasy\&.filename\fP"
.br
.ti -1c
.RI "\fBGWeasy\&.level\fP"
.br
.ti -1c
.RI "\fBGWeasy\&.format\fP"
.br
.ti -1c
.RI "str \fBGWeasy\&.HISTORY_FILE\fP = 'gravfetch_history\&.json'"
.br
.ti -1c
.RI "\fBGWeasy\&.root\fP = tk\&.Tk()"
.br
.ti -1c
.RI "\fBGWeasy\&.app\fP = \fBApplication\fP(\fBroot\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GWeasy from the source code\&.
