.TH "GWeasy" 3 "Version v3.0.1" "GWeasy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GWeasy
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.ti -1c
.RI "class \fBFFT\fP"
.br
.ti -1c
.RI "class \fBGravfetchApp\fP"
.br
.ti -1c
.RI "class \fBGWOSCApp\fP"
.br
.ti -1c
.RI "class \fBOmicronApp\fP"
.br
.ti -1c
.RI "class \fBOmiviz\fP"
.br
.ti -1c
.RI "class \fBPSDs\fP"
.br
.ti -1c
.RI "class \fBSpectrogram\fP"
.br
.ti -1c
.RI "class \fBTerminalFrame\fP"
.br
.ti -1c
.RI "class \fBTimeSrswaveform\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.ti -1c
.RI "str \fBHISTORY_FILE\fP = 'gravfetch_history\&.json'"
.br
.ti -1c
.RI "\fBroot\fP = tk\&.Tk()"
.br
.ti -1c
.RI "\fBapp\fP = \fBApplication\fP(\fBroot\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "GWeasy\&.app = \fBApplication\fP(\fBroot\fP)"

.PP
Definition at line \fB2316\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.filename"

.PP
Definition at line \fB27\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.format"

.PP
Definition at line \fB29\fP of file \fBGWeasy\&.py\fP\&.
.SS "str GWeasy\&.HISTORY_FILE = 'gravfetch_history\&.json'"

.PP
Definition at line \fB31\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.level"

.PP
Definition at line \fB28\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.root = tk\&.Tk()"

.PP
Definition at line \fB2315\fP of file \fBGWeasy\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GWeasy from the source code\&.
