.TH "GWeasy.Application" 3 "Version v3.0.1" "GWeasy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GWeasy.Application
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBroot\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBroot\fP = root"
.br
.ti -1c
.RI "\fBnotebook\fP = ttk\&.Notebook(self\&.root)"
.br
.ti -1c
.RI "\fBgwosc_tab\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBgravfetch_tab\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBomicron_tab\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBomiviz_tab\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBTimeSeriesWav\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBFFT\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBPSDs\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBSpectrogram\fP = ttk\&.Frame(self\&.notebook)"
.br
.ti -1c
.RI "\fBgravfetch_app\fP = \fBGravfetchApp\fP(self\&.gravfetch_tab)"
.br
.ti -1c
.RI "\fBomicron_app\fP = \fBOmicronApp\fP(self\&.omicron_tab)"
.br
.ti -1c
.RI "\fBomiviz_app\fP = \fBOmiviz\fP(self\&.omiviz_tab)"
.br
.ti -1c
.RI "\fBTimeSeriesWav_app\fP = \fBTimeSrswaveform\fP(self\&.TimeSeriesWav)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBGWeasy\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GWeasy\&.Application\&.__init__ ( self,  root)"

.PP
Definition at line \fB36\fP of file \fBGWeasy\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GWeasy\&.Application\&.FFT = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB65\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.gravfetch_app = \fBGravfetchApp\fP(self\&.gravfetch_tab)"

.PP
Definition at line \fB75\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.gravfetch_tab = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB51\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.gwosc_tab = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB47\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.notebook = ttk\&.Notebook(self\&.root)"

.PP
Definition at line \fB41\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.omicron_app = \fBOmicronApp\fP(self\&.omicron_tab)"

.PP
Definition at line \fB76\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.omicron_tab = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB55\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.omiviz_app = \fBOmiviz\fP(self\&.omiviz_tab)"

.PP
Definition at line \fB77\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.omiviz_tab = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB59\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.PSDs = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB68\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.root = root"

.PP
Definition at line \fB37\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.Spectrogram = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB71\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.TimeSeriesWav = ttk\&.Frame(self\&.notebook)"

.PP
Definition at line \fB62\fP of file \fBGWeasy\&.py\fP\&.
.SS "GWeasy\&.Application\&.TimeSeriesWav_app = \fBTimeSrswaveform\fP(self\&.TimeSeriesWav)"

.PP
Definition at line \fB78\fP of file \fBGWeasy\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GWeasy from the source code\&.
